server:
  port: 8771

spring:
  application:
    name: system-service
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

