spring:
  application:
    name: uaa-service
  datasource:
    name: MYDB
    sql-script-encoding: utf-8
    driver-class-name:   com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zp_self?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30