server:
  port: 8763

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
  redis:
    database: 0
    host: 127.0.0.1
    password: 'issmart'
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 2000ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30



feign.hystrix.enabled: true

ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000
###配置请求超时时间
hystrix:
                                     command:
                                       default:
                                         execution:
                                           isolation:
                                             thread:
                                               timeoutInMilliseconds: 7000